# Generated by Django 5.1.3 on 2024-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='AireComprimido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiscosExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('capacidad', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Microfono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('cableado', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=20)),
                ('cargador', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('cableado', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('procesador', models.CharField(max_length=15)),
                ('ram', models.CharField(max_length=15)),
                ('capacidad_ram', models.CharField(max_length=8)),
                ('almacenamiento', models.CharField(max_length=15)),
                ('tarjeta_video', models.CharField(max_length=15)),
                ('estado_notebook', models.CharField(max_length=10)),
                ('cargador_disponible', models.CharField(max_length=5)),
                ('estado_bateria', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('slots_memorias', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('sockets', models.CharField(max_length=40)),
                ('chipset', models.CharField(max_length=30)),
                ('formato', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('capacidad', models.CharField(max_length=8)),
                ('velocidad', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Refrigeracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('sockets', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=15)),
                ('cableado', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=8)),
            ],
        ),
    ]
